### ISSUE TITLE
Can't build the package

### ISSUE THREAD

**Issue by itsmedralpha** [roboception/rc_visard_opencv_example#2]
[ 12%] Building CXX object rc_visard_opencv_example/CMakeFiles/rc_visard_opencv_example.dir/gc_cleaner.cc.o
[ 25%] Building CXX object rc_visard_opencv_example/CMakeFiles/rc_visard_opencv_example.dir/gc_receiver.cc.o
In file included from /home/dralpha/rc_visard_opencv_example/include/rc_visard_opencv_example/gc_receiver.h:39,
                 from /home/dralpha/rc_visard_opencv_example/rc_visard_opencv_example/gc_receiver.cc:36:
/home/dralpha/rc_visard_opencv_example/include/rc_visard_opencv_example/image.h:67:5: error: ‘cv’ does not name a type
   67 |     cv::Mat data_;
      |     ^~
/home/dralpha/rc_visard_opencv_example/include/rc_visard_opencv_example/image.h:74:22: error: ‘cv’ has not been declared
   74 |     Image(Type type, cv::Mat data, Timestamp timestamp) :
      |                      ^~
/home/dralpha/rc_visard_opencv_example/include/rc_visard_opencv_example/image.h:74:30: error: expected ‘,’ or ‘...’ before ‘data’
   74 |     Image(Type type, cv::Mat data, Timestamp timestamp) :
      |                              ^~~~
/home/dralpha/rc_visard_opencv_example/include/rc_visard_opencv_example/image.h: In constructor ‘Image::Image(Image::Type, int)’:
/home/dralpha/rc_visard_opencv_example/include/rc_visard_opencv_example/image.h:75:22: error: class ‘Image’ does not have any field named ‘data_’
   75 |         type_(type), data_(std::move(data)), timestamp_(timestamp)
      |                      ^~~~~
/home/dralpha/rc_visard_opencv_example/include/rc_visard_opencv_example/image.h:75:38: error: ‘data’ was not declared in this scope
   75 |         type_(type), data_(std::move(data)), timestamp_(timestamp)
      |                                      ^~~~
/home/dralpha/rc_visard_opencv_example/include/rc_visard_opencv_example/image.h:75:57: error: ‘timestamp’ was not declared in this scope; did you mean ‘timestamp_’?
   75 |         type_(type), data_(std::move(data)), timestamp_(timestamp)
      |                                                         ^~~~~~~~~
      |                                                         timestamp_
/home/dralpha/rc_visard_opencv_example/include/rc_visard_opencv_example/image.h: At global scope:
/home/dralpha/rc_visard_opencv_example/include/rc_visard_opencv_example/image.h:82:13: error: ‘cv’ has not been declared
   82 |   ImageBase(cv::Mat data, Timestamp timestamp) :
      |             ^~
/home/dralpha/rc_visard_opencv_example/include/rc_visard_opencv_example/image.h:82:20: error: expected ‘)’ before ‘data’
   82 |   ImageBase(cv::Mat data, Timestamp timestamp) :
      |            ~       ^~~~~
      |                    )
/home/dralpha/rc_visard_opencv_example/include/rc_visard_opencv_example/image.h:84:3: error: expected unqualified-id before ‘{’ token
   84 |   {}
      |   ^
/home/dralpha/rc_visard_opencv_example/include/rc_visard_opencv_example/image.h:151:18: error: ‘cv’ has not been declared
  151 |   DisparityImage(cv::Mat data, Timestamp timestamp,
      |                  ^~
/home/dralpha/rc_visard_opencv_example/include/rc_visard_opencv_example/image.h:151:25: error: expected ‘)’ before ‘data’
  151 |   DisparityImage(cv::Mat data, Timestamp timestamp,
      |                 ~       ^~~~~
      |                         )
/home/dralpha/rc_visard_opencv_example/include/rc_visard_opencv_example/image.h:153:44: error: expected unqualified-id before ‘,’ token
  153 |       ImageBase{std::move(data), timestamp},
      |                                            ^
In file included from /home/dralpha/rc_visard_opencv_example/rc_visard_opencv_example/gc_receiver.cc:36:
/home/dralpha/rc_visard_opencv_example/include/rc_visard_opencv_example/gc_receiver.h:155:10: error: ‘vector’ in namespace ‘std’ does not name a template type
  155 |     std::vector<std::unique_ptr<ImageReceiver>> image_receivers_;
      |          ^~~~~~
/home/dralpha/rc_visard_opencv_example/include/rc_visard_opencv_example/gc_receiver.h:48:1: note: ‘std::vector’ is defined in header ‘<vector>’; did you forget to ‘#include <vector>’?
   47 | #include <unordered_map>
  +++ |+#include <vector>
   48 | 
/home/dralpha/rc_visard_opencv_example/rc_visard_opencv_example/gc_receiver.cc: In constructor ‘GcReceiver::GcReceiver(GcReceiver&&)’:
/home/dralpha/rc_visard_opencv_example/rc_visard_opencv_example/gc_receiver.cc:87:5: error: class ‘GcReceiver’ does not have any field named ‘image_receivers_’
   87 |     image_receivers_(std::move(image_receivers_))
      |     ^~~~~~~~~~~~~~~~
/home/dralpha/rc_visard_opencv_example/rc_visard_opencv_example/gc_receiver.cc:87:32: error: ‘image_receivers_’ was not declared in this scope; did you mean ‘ImageReceiver’?
   87 |     image_receivers_(std::move(image_receivers_))
      |                                ^~~~~~~~~~~~~~~~
      |                                ImageReceiver
/home/dralpha/rc_visard_opencv_example/rc_visard_opencv_example/gc_receiver.cc:89:9: error: ‘class GcReceiver’ has no member named ‘image_receivers_’
   89 |   other.image_receivers_.clear();
      |         ^~~~~~~~~~~~~~~~
/home/dralpha/rc_visard_opencv_example/rc_visard_opencv_example/gc_receiver.cc: In member function ‘bool GcReceiver::initializeStreams(const ReceiverFactories&)’:
/home/dralpha/rc_visard_opencv_example/rc_visard_opencv_example/gc_receiver.cc:184:5: error: ‘image_receivers_’ was not declared in this scope; did you mean ‘image_receivers’?
  184 |     image_receivers_ = std::move(image_receivers);
      |     ^~~~~~~~~~~~~~~~
      |     image_receivers
/home/dralpha/rc_visard_opencv_example/rc_visard_opencv_example/gc_receiver.cc: In member function ‘std::unique_ptr<ImageSet> GcReceiver::receive(std::chrono::milliseconds)’:
/home/dralpha/rc_visard_opencv_example/rc_visard_opencv_example/gc_receiver.cc:245:35: error: ‘image_receivers_’ was not declared in this scope; did you mean ‘ImageReceiver’?
  245 |       for (const auto &receiver : image_receivers_)
      |                                   ^~~~~~~~~~~~~~~~
      |                                   ImageReceiver
/home/dralpha/rc_visard_opencv_example/rc_visard_opencv_example/gc_receiver.cc:260:16: error: ‘all_of’ is not a member of ‘std’
  260 |       if (std::all_of(image_receivers_.begin(), image_receivers_.end(),
      |                ^~~~~~
/home/dralpha/rc_visard_opencv_example/rc_visard_opencv_example/gc_receiver.cc:260:23: error: ‘image_receivers_’ was not declared in this scope; did you mean ‘ImageReceiver’?
  260 |       if (std::all_of(image_receivers_.begin(), image_receivers_.end(),
      |                       ^~~~~~~~~~~~~~~~
      |                       ImageReceiver
/home/dralpha/rc_visard_opencv_example/rc_visard_opencv_example/gc_receiver.cc:286:35: error: ‘image_receivers_’ was not declared in this scope; did you mean ‘ImageReceiver’?
  286 |       for (const auto &receiver : image_receivers_)
      |                                   ^~~~~~~~~~~~~~~~
      |                                   ImageReceiver
make[2]: *** [rc_visard_opencv_example/CMakeFiles/rc_visard_opencv_example.dir/build.make:90: rc_visard_opencv_example/CMakeFiles/rc_visard_opencv_example.dir/gc_receiver.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:161: rc_visard_opencv_example/CMakeFiles/rc_visard_opencv_example.dir/all] Error 2
make: *** [Makefile:166: all] Error 2

**Comment by flixr** [comment]
Can you please provide some context?
What system are you building on? Versions of OpenCV, etc?

**Comment by denizsoysal** [comment]
Same problem here, were you able to solve it ?

**Comment by flixr** [comment]
@denizsoysal can you please provide some context and details on your system, OpenCV version, etc..?

**Comment by denizsoysal** [comment]
@flixr I have opencv 4.5.4 and ubuntu 22.04

**Comment by flixr** [comment]
Should be fixed in master.
